### ISSUE TITLE
Clarification needed on `enemy_state` handling due to missing `enemy_state.hpp`

### ISSUE THREAD

**Issue by Lingzilla** [julyfun/rm.cv.fans#1]
Hi, I've recently been improving my anti-top algorithm and after some searching came across this repository of yours.
  
  In reading through the code, I'm a bit confused about the content and handling of `enemy_state` because of the missing `aimer/auto_aim/predictor/enemy/enemy_state.hpp`, and I was wondering if you'd be interested in helping me out. �

**Comment by julyfun** [comment]
现在已经补充了很多基础组件哦~
